name: hostel_mess_2
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path: ^1.9.0
  get_it: ^8.0.3
  flutter_bloc: ^9.1.0
  google_fonts: ^6.2.1
  equatable: ^2.0.7
  mobile_scanner: ^7.1.2
  intl: ^0.20.2
  bloc: ^9.1.0
  meta: ^1.16.0
  collection: ^1.19.1
  csv: ^6.0.0
  permission_handler: ^12.0.1
  file_saver: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
